name: Firebase CD

on:
  push:
    branches:
      - master

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '16.x'
      - name: Create env file
        run: |
          touch .env
          echo emailServiceId=${{ secrets.emailServiceId }} >> .env
          echo emailTemplateId=${{ secrets.emailTemplateId }} >> .env
          echo emailUserId=${{ secrets.emailUserId }} >> .env
          echo firebaseConfig=${{ secrets.FIREBASE_WEB_CONFIG }} >> .env
          cat .env
      - run: npm install
      - run: npm run build
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
