name: Firebase CD

on:
  push:
    branches:
      - master

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '16.x'
      - name: Create env file
        run: |
          touch .env
          echo EMAIL_SERVICE_ID=${{ secrets.EMAIL_SERVICE_ID }} >> .env
          echo EMAIL_TEMPLATE_ID=${{ secrets.EMAIL_TEMPLATE_ID }} >> .env
          echo EMAIL_USER_ID=${{ secrets.EMAIL_USER_ID }} >> .env
          echo FIREBASE_WEB_CONFIG=${{ secrets.FIREBASE_WEB_CONFIG }} >> .env
          echo AUTH_EMAIL=${{ secrets.AUTH_EMAIL }} >> .env
          echo AUTH_PASS=${{ secrets.AUTH_PASS }} >> .env
          cat .env
      - run: npm install
      - run: npm run build
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
